# Use root/example as user/password credentials
version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./images:/app/images
    depends_on:
      - db
    ports:
      - '3200:3200'

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_PASSWORD: snippetbox
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: snippetbox
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
      # - ./db:/docker-entrypoint-initdb.d