# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_PASSWORD: snippetbox
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: snippetbox
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      # - ./mysql-data/init.sql:/docker-entrypoint-initdb.d/init.sql